/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 blobs.glb 
*/

import React from 'react'
import { useGLTF, Float } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/blobs.glb')
  return (
    <group {...props} dispose={null}>

      <Float
        speed={0.6} // animation speed
        rotationIntensity={10} // how much it rotates
        floatIntensity={1} // how much it floats up/down
        floatingRange={[-0.4, 0.4]} // optional: limits vertical float
      >
        <mesh geometry={nodes.Icosphere.geometry} material={materials['Material.004']} position={[3.247, -2.243, -1.024]} rotation={[-0.117, -0.036, -0.021]} scale={1.404} />

      </Float>

      <Float
        speed={0.3} // animation speed
        rotationIntensity={10} // how much it rotates
        floatIntensity={2} // how much it floats up/down
        floatingRange={[-0.2, 0.3]} // optional: limits vertical float
      >
        <mesh geometry={nodes.Icosphere001.geometry} material={materials['Material.002']} position={[-1.261, 1.276, 1.944]} rotation={[0.79, 0.275, 0.02]} scale={[0.955, 0.964, 0.955]} />

      </Float>

      <Float
        speed={0.5} // animation speed
        rotationIntensity={10} // how much it rotates
        floatIntensity={2} // how much it floats up/down
        floatingRange={[-0.3, 0.2]} // optional: limits vertical float
      >
        <mesh geometry={nodes.Icosphere002.geometry} material={materials['Material.001']} position={[2.637, 2.682, -2.858]} rotation={[0.43, 0.102, 0.232]} scale={[1.747, 0.979, 1.747]} />

      </Float>

      <Float
        speed={0.4} // animation speed
        rotationIntensity={10} // how much it rotates
        floatIntensity={2} // how much it floats up/down
        floatingRange={[-0.8, 0.5]} // optional: limits vertical float
      >
        <mesh geometry={nodes.Icosphere004.geometry} material={materials['Material.007']} position={[1.07, -0.009, 2.375]} rotation={[-0.59, -0.148, -0.142]} scale={[0.807, 1.057, 1.057]} />

      </Float>

      <Float
        speed={0.7} // animation speed
        rotationIntensity={10} // how much it rotates
        floatIntensity={2} // how much it floats up/down
        floatingRange={[-0.6, 0.3]} // optional: limits vertical float
      >
        <mesh geometry={nodes.Icosphere005.geometry} material={materials['Material.006']} position={[-4.357, -1.031, 1.37]} rotation={[-2.273, 0.021, -0.631]} scale={[2.359, 2.359, 1.065]} />

      </Float>

      <Float
        speed={0.6} // animation speed
        rotationIntensity={10} // how much it rotates
        floatIntensity={2} // how much it floats up/down
        floatingRange={[-0.5, 0.8]} // optional: limits vertical float
      >
        <mesh geometry={nodes.Icosphere006.geometry} material={materials['Material.003']} position={[-5.724, 2.268, -1.313]} rotation={[-0.776, -0.059, -0.279]} scale={0.694} />

      </Float>

      <Float
        speed={0.4} // animation speed
        rotationIntensity={10} // how much it rotates
        floatIntensity={2} // how much it floats up/down
        floatingRange={[-0.7, 0.3]} // optional: limits vertical float
      >
        <mesh geometry={nodes.Icosphere003.geometry} material={materials['Material.005']} position={[4.989, -0.391, -4.214]} rotation={[-0.6, -0.065, -0.213]} scale={[0.755, 0.864, 0.755]} />

      </Float>
    </group>
  )
}

useGLTF.preload('/blobs.glb')